In [17]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


In [18]:
import random
import copy

def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.
    """
   

              ### YOUR CODE HERE
     
# Loop through the sudoku and record the locations of the empty cells (row, col)
      ### YOUR CODE HERE  
    return suduko_solver
        

def get_empty_cells(board):
    x = np.where(board == 0)
    empty_cells = np.column_stack(x)
    print(empty_cells)
    return empty_cells
  

def fill_empty_cells(board, empty_cells):  
    for x in empty_cells:
        #print(empty_cells)
        values = list(range(1,10))
        #print(values)
        for i in values:
            sudoku[x] = values[0]
            #print(x)
            return 
            
def is_valid_col(board, empty_cells):
    for x in empty_cells:
        i = empty_cells[0]
        for i in range(len(sudoku)):
            #print(i)
            return 
        #return is_valid(bool(col))
    
empty_cells = get_empty_cells(sudoku)
#fill_empty_cells(sudoku, empty_cells)
#is_valid_col(sudoku, empty_cells)

[[ 0  0  1]
 [ 0  1  1]
 [ 0  2  7]
 [ 0  7  1]
 [ 0  8  3]
 [ 1  0  0]
 [ 1  0  7]
 [ 1  1  4]
 [ 1  3  6]
 [ 1  4  1]
 [ 2  2  0]
 [ 2  3  7]
 [ 2  4  2]
 [ 2  5  2]
 [ 2  8  4]
 [ 3  0  5]
 [ 3  4  1]
 [ 3  4  8]
 [ 3  6  2]
 [ 3  6  4]
 [ 4  2  1]
 [ 4  2  5]
 [ 4  2  6]
 [ 4  5  5]
 [ 4  6  7]
 [ 5  0  4]
 [ 5  0  6]
 [ 5  1  3]
 [ 5  1  5]
 [ 5  7  6]
 [ 6  0  2]
 [ 6  0  3]
 [ 6  2  6]
 [ 6  4  6]
 [ 6  8  3]
 [ 7  0  7]
 [ 7  1  4]
 [ 7  2  4]
 [ 7  6  4]
 [ 7  8  7]
 [ 8  1  0]
 [ 8  2  1]
 [ 8  4  2]
 [ 8  6  1]
 [ 8  7  7]
 [ 9  0  1]
 [ 9  0  6]
 [ 9  1  5]
 [ 9  2  7]
 [ 9  8  0]
 [10  0  5]
 [10  1  8]
 [10  4  3]
 [10  5  7]
 [10  8  2]
 [11  0  0]
 [11  0  2]
 [11  1  2]
 [11  3  0]
 [11  8  5]
 [12  0  3]
 [12  3  3]
 [12  4  6]
 [12  6  2]
 [12  7  8]
 [13  0  0]
 [13  4  4]
 [13  5  6]
 [13  6  7]
 [13  8  8]
 [14  0  2]
 [14  4  3]
 [14  4  4]
 [14  4  7]
 [14  6  6]]
